name: 'Publish to google play console'
description: 'Publish new app version to google play console'
inputs:
  config_file: # Path of config file containing publish configs
    description: 'Path of the file'
    required: true
  playstore_encrypted_file: # Service account details encrypted using gpg
    description: 'Service account creds'
    required: true
  playstore_decryption_pwd: # GPG decryption password
    required: true
    description: 'Key to decrypt playstore_encrypted_file'
outputs:
  message:
    value: "Successful"
    description: 'Some description'
runs:
  using: "composite"
  steps:
    - name: Setup python
      uses: actions/setup-python@v4
      with:
        cache: 'pip'

    - run: ls -a
      shell: bash

    - shell: bash
      run: |
        echo $ENV
        echo $GITHUB_ACTION_PATH

    - run: cd src && python main.py
      shell: bash

