name: 'Publish to google play console'
description: 'Publish new app version to google play console'
inputs:
  config_file: # Path of config file containing publish configs
    description: 'Path of the file'
    required: true
  playstore_secret: # Service account details
    description: 'Service account creds'
    required: true
outputs:
  message:
    value: 'Successful'
    description: 'Samle description'
runs:
  using: "composite"
  steps:
    - name: Clone the repo
      uses: actions/checkout@v3

    - name: setup python
      uses: actions/setup-python@v3

    - name: install python packages
      shell: bash
      run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
    - id: random-number-generator
      shell: bash
      run: python main.py  ${{ inputs.config_file }} ${{ inputs.playstore_secret }}

